### ISSUE TITLE
What is the conceptual difference between SYMP and HPO?

### ISSUE THREAD

**Issue by matentzn** [DiseaseOntology/SymptomOntology#10]
When people ask OBO about which ontology to use, it would be good if we could give a solid answer. How would you explain to people when they should use HPO vs SYMP? Do you maintaining a mapping between the two? They seem sort of.. the same?

**Comment by lschriml** [comment]
The DO follows the clinical definitions of phenotype and symptom.

HPO has integrated a number of symptoms over the years. Initially a few dozen, I have not checked lately, but many symptoms are likely now also in HPO. The concept of phenotype has broadened in the HPO to include symptoms and diseases (e.g cancers). 

Conceptually, a phenotype and a symptom are not at all the same. 

a phenotype: the set of observable characteristics of an individual resulting from the interaction of its genotype with the environment.

a symptom:  is a perceived change in function, sensation, loss, disturbance or appearance reported by a patient indicative of a disease. 
             -- symptoms are not the result of genotype and environment interactions
             -- examples: fever and pain

**Comment by matentzn** [comment]
Interesting, thank you! I do not know yet what is best here, like maintaining a formal mapping or something; but I was not aware of this distinction of symptom and phenotype. I thought they kinda both mean the same.
