### ISSUE TITLE
Annotate SYMP_0000462 as ontology root with IAO_0000700

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/SymptomOntology#13]
Request to have added: by @cthoyt 

@allenbaron - to review and update SYMP

Add a new annotation property [has ontology root term (IAO:0000700)](http://purl.obolibrary.org/obo/IAO_0000700) to the ontology
Apply this property at the ontology level to annotate [symptom (SYMP:0000462)](http://purl.obolibrary.org/obo/SYMP_0000462) as the root.
It's true that this is already logically the root element, but this makes it explicit.

Why this is helpful

the Ontology Lookup Service uses this to help better display ontologies
if SYMP_0000462 ever is aligned with an upper ontology like BFO, it still will be the thing shown on OLS as the "root"
this will be generally useful for things like alignment with COB since it makes it easier to figure out where the work will be

**Comment by allenbaron** [comment]
Completed with #12.
