### ISSUE TITLE
Terms without definitions

### ISSUE THREAD

**Issue by msabanluc** [DiseaseOntology/SymptomOntology#18]
Hello,
I've noticed a couple terms in the ontology lacking definitions and would like to propose the following definitions for the respective terms.

**[SYMP_0000421](http://purl.obolibrary.org/obo/SYMP_0000421) - Hematochezia**
"_is a feces and droppings symptom that is the passage of fresh blood per anus, usually in or with stools._"
[Description Reference](https://www.ncbi.nlm.nih.gov/books/NBK201/)

 **[SYMP_0000295](http://purl.obolibrary.org/obo/SYMP_0000295) - Hepatic abscess**
"_is a liver symptom that is defined as a pus-filled mass in the liver that can develop from injury to the liver or an intraabdominal infection disseminated from the portal circulation._"
[Description Reference](https://www.ncbi.nlm.nih.gov/books/NBK538230/#:~:text=A%20liver%20abscess%20is%20defined,caused%20by%20parasites%20and%20fungi.)

Please let me know if there is a better way to go about these proposals.
Thank you!

**Comment by allenbaron** [comment]
Thanks Michael. We appreciate your contribution. If you have an ORCiD identifier and would look to add it so that we can recognize you as contributing, please share it here.

Ideally, we like to have at least one quality, online source to support each definition we write. If you happen to know of any, we'd appreciate you sharing those as well. Either way, we'll review these definitions and get them added.

Thanks again!

**Comment by msabanluc** [comment]
Hi Allen, here is my [ORCiD](https://orcid.org/0009-0002-8031-4669).

For **SYMP_0000421 - Hematochezia**, please refer to the [Clinical Methods, 3rd edition Book](https://www.ncbi.nlm.nih.gov/books/NBK201/), specifically [Chapter 85](https://www.ncbi.nlm.nih.gov/books/NBK411/#A2794).

For **SYMP_0000295 - Hepatic abscess**, please refer to [this book on liver abscesses](https://www.ncbi.nlm.nih.gov/books/NBK538230/#:~:text=A%20liver%20abscess%20is%20defined,caused%20by%20parasites%20and%20fungi.).


Please let me know if you have any questions or if I can provide you with any further information.
Thank you and have a great rest of your day!

**Comment by csbjohnson** [comment]
Hi @msabanluc,

I've added the requested definitions and supporting sources, and they'll be reflected in our next release. 

Thank you!
