### ISSUE TITLE
doubling symptoms/ synonyms

### ISSUE THREAD

**Issue by atadria** [DiseaseOntology/SymptomOntology#5]
Hi, 
I found that some terms have other therms labels/synonyms as their synonyms:
1) SYMP_0000445 faint -> hasExactSynonym -> syncope (SYMP_0000407)
2) SYMP_0000423 pyrosis -> hasExactSynonym -> heartburn (SYMP_0000439)
3) SYMP_0000639 rectorrhagia -> hasExactSynonym -> hematochezia (SYMP_0000421)
4) SYMP_0000476 loss of weight -> hasExactSynonym -> weight loss (SYMP_0000178)
5) two classes have the same synonym
    SYMP_0000521 enlargement of lymph nodes -> hasExactSynonym -> lymphadenopathy 
    SYMP_0019142 adenopathy -> hasExactSynonym -> lymphadenopathy 

I think classes from (1-4) should be merged, to remove redundancy.

Additionally there is problem with class weight loss and it's structure: 

weight loss
      |__abnormal loss of weight and underweight
             |__loss of weight
             |      |__acute weight loss
             |__underweight

my suggestion is to replace it with something like this (with aggregated weight problems and added obesity) : 

weight symptom
      |__loss of weight
      |       |__acute weight loss (abnormal weight loss)
      |__underweight
      |__gain of weight
      |      |__acute weight gain(abnormal weight gain) 
      |__obesity

**Comment by melodyswen** [comment]
Hi! 

Thank you for your comment - we'll review this and get back to you!

**Comment by melodyswen** [comment]
Hi!
For #1-3,  I think that the more colloquial synonyms (heartburn, faint, etc.) should be merged, and kept as symptoms. I will check to see how the separate synonyms are used in the wider ontology and Disease Ontology. 

4. I also agree that the weight loss class structure should be reorganized - 'weight symptom' would mimic the naming structure of other parents. 

5. I'll review #5. 

Thank you for your helpful comments!

**Comment by melodyswen** [comment]
As for #5, adenopathy and lymphadenopathy are exact synonyms. I am removing lymphadenopathy as a synonym of 'enlargement of lymph nodes', as lymphadenopathy presents as an enlargement of >1 lymph nodes due to infection.
