### ISSUE TITLE
Importing into Neo4j

### ISSUE THREAD

**Issue by hasnainroopawalla** [DiseaseOntology/SymptomOntology#6]
How do I import the symp.owl ontology into my Neo4j Graph Database?

**Comment by lschriml** [comment]
Hello Hasnain,
   Thank you for your interest in the Symptom ontology.
Here are a few resources that provide information pertinent to your request:

https://neo4j.com/docs/labs/nsmntx/current/importing-ontologies/

https://community.neo4j.com/t/import-owl-individuals-to-neo4j/11873/2

https://medium.com/neo4j/importing-rdfs-owl-ontologies-into-neo4j-23e4e28ebbad

Cheers,
Lynn

**Comment by hasnainroopawalla** [comment]
Thanks will go through them!
