### ISSUE TITLE
Question about SyOID:10057

### ISSUE THREAD

**Issue by cthoyt** [DiseaseOntology/SymptomOntology#7]
Many terms in the symptom ontology have SyOID xrefs. What resource does this prefix correspond to?

**Comment by lschriml** [comment]
Hello Charles,
  The SyOID was a unique ID space that was used when I first built the symptom ontology as part of the Gemina (now retired) database in 2006/2007.

Cheers,
Lynn

**Comment by cthoyt** [comment]
Thank you for the information!
