### ISSUE TITLE
NTR: paroxysmal cough

### ISSUE THREAD

**Issue by hectorguzor** [DiseaseOntology/SymptomOntology#9]
Hello, the [CMI-PB](https://www.cmi-pb.org/) project at LJI is in need of an ontology term for 'paroxysmal cough'. Would it be possible to create a new term for this? Below is a textual definition and parent class:

**paroxysmal cough**: A persistent cough with sudden onset due to difficulty expelling thick mucus from the tracheobronchial tree. This type of cough is associated with diseases such as Pertussis (Whooping Cough). 

Subclass of = cough

Thanks

**Comment by hectorguzor** [comment]
Hi @lschriml,

I wanted to follow up on this issue. Is this a term that could go in The symptom ontology? Thanks

**Comment by lschriml** [comment]
Hello Hector,
  apologies for the delay. 
Yes, we can add this term. 
Cheers,
Lynn

**Comment by jbmunro** [comment]
Apologies for the delay.  The term has been added and will be available with the next release, which I hope to do next week.

**Comment by hectorguzor** [comment]
Thank you.

**Comment by jbmunro** [comment]
There is now a new release and the term 'paroxysmal cough' should be available.

Again - apologies for the delay.

Closing the ticket.
